# -*- coding: utf-8 -*-
"""מאגר נתונים של אטרקציות בלונדון עבור סוכן האטרקציות של זיווה."""

ATTRACTIONS = [
    {
        "name": "לונדון איי (London Eye)",
        "category": "נוף ובידור",
        "area": "South Bank",
        "price": "יקר",
        "duration_hours": 1,
        "kids_friendly": True,
        "rating": 4.5,
        "description": "גלגל ענק על גדות התמזה עם נוף פנורמי על העיר.",
    },
    {
        "name": "מגדל לונדון (Tower of London)",
        "category": "היסטוריה",
        "area": "City of London",
        "price": "יקר",
        "duration_hours": 3,
        "kids_friendly": True,
        "rating": 4.7,
        "description": "מבצר עתיק בן 1000 שנה, בית תכשיטי הכתר הבריטי.",
    },
    {
        "name": "הבריטיש מיוזיאם (British Museum)",
        "category": "מוזיאונים",
        "area": "Bloomsbury",
        "price": "חינם",
        "duration_hours": 3,
        "kids_friendly": True,
        "rating": 4.8,
        "description": "אחד המוזיאונים הגדולים בעולם, כניסה חינם, אוצרות מכל העולם.",
    },
    {
        "name": "ארמון בקינגהאם (Buckingham Palace)",
        "category": "היסטוריה",
        "area": "Westminster",
        "price": "בינוני",
        "duration_hours": 2,
        "kids_friendly": True,
        "rating": 4.4,
        "description": "מעון המלוכה הרשמי, מפורסם בטקס חילופי המשמרות.",
    },
    {
        "name": "וסטמינסטר אבי (Westminster Abbey)",
        "category": "היסטוריה",
        "area": "Westminster",
        "price": "יקר",
        "duration_hours": 2,
        "kids_friendly": True,
        "rating": 4.6,
        "description": "כנסייה גותית מרשימה, מקום הכתרת מלכי בריטניה.",
    },
    {
        "name": "בן בן (Big Ben) ובית הפרלמנט",
        "category": "נוף ובידור",
        "area": "Westminster",
        "price": "חינם",
        "duration_hours": 1,
        "kids_friendly": True,
        "rating": 4.6,
        "description": "מגדל השעון המפורסם בעולם, נצפה מבחוץ בחינם.",
    },
    {
        "name": "טייט מודרן (Tate Modern)",
        "category": "מוזיאונים",
        "area": "South Bank",
        "price": "חינם",
        "duration_hours": 2,
        "kids_friendly": False,
        "rating": 4.5,
        "description": "מוזיאון לאמנות מודרנית וחדשנית בתוך תחנת כוח ישנה.",
    },
    {
        "name": "קמדן מרקט (Camden Market)",
        "category": "קניות ואוכל",
        "area": "Camden",
        "price": "חינם",
        "duration_hours": 2,
        "kids_friendly": True,
        "rating": 4.3,
        "description": "שוק צבעוני עם אוכל רחוב, בגדים ואומנות מכל העולם.",
    },
    {
        "name": "בורו מרקט (Borough Market)",
        "category": "קניות ואוכל",
        "area": "South Bank",
        "price": "בינוני",
        "duration_hours": 1,
        "kids_friendly": True,
        "rating": 4.6,
        "description": "שוק האוכל המפורסם ביותר בלונדון, טעימות ומעדנים.",
    },
    {
        "name": "הייד פארק (Hyde Park)",
        "category": "טבע ופארקים",
        "area": "West London",
        "price": "חינם",
        "duration_hours": 2,
        "kids_friendly": True,
        "rating": 4.7,
        "description": "אחד הפארקים הגדולים בלונדון, אגם, פסלים ופינות ירוקות.",
    },
    {
        "name": "גני קיו (Kew Gardens)",
        "category": "טבע ופארקים",
        "area": "Richmond",
        "price": "בינוני",
        "duration_hours": 3,
        "kids_friendly": True,
        "rating": 4.7,
        "description": "גן בוטני מדהים עם אתר מורשת עולמית של אונסק\"ו.",
    },
    {
        "name": "מדאם טוסו (Madame Tussauds)",
        "category": "נוף ובידור",
        "area": "Marylebone",
        "price": "יקר",
        "duration_hours": 2,
        "kids_friendly": True,
        "rating": 4.1,
        "description": "מוזיאון פסלי השעווה המפורסם עם דמויות סלבריטאים.",
    },
    {
        "name": "נטורל היסטורי מיוזיאום (Natural History Museum)",
        "category": "מוזיאונים",
        "area": "South Kensington",
        "price": "חינם",
        "duration_hours": 3,
        "kids_friendly": True,
        "rating": 4.8,
        "description": "מוזיאון ענק עם שלד דינוזאור ותערוכות טבע מרהיבות, אהוב על ילדים.",
    },
    {
        "name": "קתדרלת סנט פול (St Paul's Cathedral)",
        "category": "היסטוריה",
        "area": "City of London",
        "price": "יקר",
        "duration_hours": 2,
        "kids_friendly": True,
        "rating": 4.7,
        "description": "קתדרלה מרשימה עם כיפה איקונית ונוף פנורמי מלמעלה.",
    },
    {
        "name": "טאואר ברידג' (Tower Bridge)",
        "category": "נוף ובידור",
        "area": "City of London",
        "price": "בינוני",
        "duration_hours": 1,
        "kids_friendly": True,
        "rating": 4.6,
        "description": "הגשר האייקוני מעל התמזה, עם רצפת זכוכית שקופה.",
    },
    {
        "name": "שרלוק הולמס מוזיאום",
        "category": "מוזיאונים",
        "area": "Marylebone",
        "price": "בינוני",
        "duration_hours": 1,
        "kids_friendly": True,
        "rating": 4.2,
        "description": "ביתו של הבלש המפורסם ברחוב בייקר 221B.",
    },
    {
        "name": "וורנר ברוס סטודיו טור - הארי פוטר",
        "category": "נוף ובידור",
        "area": "מחוץ ללונדון (Watford)",
        "price": "יקר",
        "duration_hours": 4,
        "kids_friendly": True,
        "rating": 4.9,
        "description": "סיור מאחורי הקלעים של סרטי הארי פוטר, דורש נסיעה קצרה מהעיר.",
    },
    {
        "name": "קובנט גארדן (Covent Garden)",
        "category": "קניות ואוכל",
        "area": "Covent Garden",
        "price": "בינוני",
        "duration_hours": 2,
        "kids_friendly": True,
        "rating": 4.6,
        "description": "כיכר תוססת עם אמני רחוב, חנויות ובתי קפה.",
    },
    {
        "name": "גרינוויץ' (Greenwich) והמרידיאן",
        "category": "טבע ופארקים",
        "area": "Greenwich",
        "price": "חינם",
        "duration_hours": 3,
        "kids_friendly": True,
        "rating": 4.7,
        "description": "פארק, מצפה כוכבים מלכותי וקו האורך אפס - אפשר לעמוד בשני חצאי כדור.",
    },
    {
        "name": "אמירייטס אייר ליין (Cable Car)",
        "category": "נוף ובידור",
        "area": "East London",
        "price": "בינוני",
        "duration_hours": 1,
        "kids_friendly": True,
        "rating": 4.3,
        "description": "רכבל מעל התמזה עם נוף ייחודי על מזרח לונדון.",
    },
]

CATEGORIES = sorted({item["category"] for item in ATTRACTIONS})
AREAS = sorted({item["area"] for item in ATTRACTIONS})
PRICE_LEVELS = ["חינם", "בינוני", "יקר"]
